### ISSUE TITLE
Unable to receive message due to FbMsgr migrating to MQTT over Websocket

### ISSUE THREAD

**Issue by blueset** [blueset/efb-fb-messenger-slave#12]
Facebook Messenger recently moved from the previous GraphQL protocol to MQTT over Websocket, which has broken the message retrieval code of upstream library `fbchat`. 

EFMS will suspend its development until `fbchat` or another reasonably usable library has adopted the new websocket protocol.

See more details here: carpedm20/fbchat#483
Relevant issue: Schmavery/facebook-chat-api#763

**Comment by ccfiel** [comment]
any updates on this? :(

**Comment by rami3l** [comment]
@blueset https://github.com/fbchat-dev/fbchat/issues/483 has been resolved, does this mean that we can close this issue?

**Comment by blueset** [comment]
Hi @rami3l, thanks for bringing this up. I think based on the update of fbchat, we can close this issue for now. 

As it is (coincidentally) a year from when the issue was first opened, I'm currently working on some other projects, and haven’t been looking at EFMS for quite a while. I hope that the API of `fbchat` did not change much drastically in the year and EFMS can still work. 

If that’s not the case, feel free to open a new issue, and I’ll try my best to handle it.
